<a href="https://colab.research.google.com/github/Maneesh290318/Machine-Learning-Algorithms/blob/main/05-regression-model-evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# # Cell number 1: House Price Prediction Case Study using Linear Regression
#
# This section outlines a case study focused on predicting house prices.
# We will use a machine learning approach to build a model that can estimate a house's price
# based on a set of its characteristics, or 'features'.
#
# ## 1. Case Study: House Price Prediction
#
# ### What are we trying to solve?
# Imagine you want to buy or sell a house, or perhaps you're a real estate investor.
# Knowing the estimated value of a property is crucial. This case study aims to build a
# predictive model that can provide such an estimate.
#
# ### How will the model work?
# Our model will take specific information about a house as input and output a predicted price.
# For this particular study, we will focus on three key feature variables of a house.
# These features could be things like:
# 1.  **Size of the house (e.g., square footage)**: Generally, larger houses cost more.
# 2.  **Number of bedrooms**: More bedrooms might indicate a higher price.
# 3.  **Location score/quality**: Houses in desirable locations tend to be more expensive.
#
# The goal is that even if only one, two, or all three of these features are provided as input,
# our model should be able to predict the house's price.
#
# ## 2. Machine Learning Approach: Supervised Learning
#
# ### What is Supervised Learning?
# Think of supervised learning as teaching a child using flashcards. You show the child a picture (input) of a dog
# and tell them, "This is a dog" (correct output/label). After seeing many examples, the child learns to identify a dog on their own.
#
# In our house price prediction case:
# -   **Inputs (Features)**: The size of the house, number of bedrooms, location score.
# -   **Outputs (Labels)**: The actual sale price of those houses.
#
# We will feed our model a dataset containing many examples of houses, each with its features and its known actual price.
# The model will learn the relationship between these features and the prices.
# Once trained, it can then predict prices for new houses it has never seen before.
#
# ### Why Supervised Learning for this problem?
# Because we have historical data where we know both the house features and their corresponding prices,
# we can 'supervise' the model's learning process. This makes supervised learning the perfect fit
# for prediction tasks like this.
#
# ## 3. Algorithm: Linear Regression
#
# ### What is Linear Regression?
# Linear Regression is one of the simplest and most fundamental algorithms in supervised learning.
# It tries to find a straight-line relationship (or a flat-plane relationship in 3D, or a hyperplane in higher dimensions)
# between our input features and the output price.
#
# Imagine plotting house size (X-axis) against house price (Y-axis).
# Linear Regression would try to draw the 'best fit' straight line through all those data points.
# This line then becomes our prediction model.
#
# The equation of a simple straight line is often written as:  `Y = mX + b`
# -   `Y` would be our predicted `House Price`.
# -   `X` would be our `House Feature` (e.g., Size).
# -   `m` is the slope of the line (how much the price changes for each unit change in size).
# -   `b` is the Y-intercept (the base price when the feature is zero, though this rarely has a real-world meaning).
#
# When we have multiple features (like our 3 features), the equation extends to:
# `Price = (m1 * Feature1) + (m2 * Feature2) + (m3 * Feature3) + b`
# Here, `m1, m2, m3` are coefficients (slopes) for each feature.
#
# ### How does Linear Regression learn?
# The algorithm calculates the 'best' values for `m1, m2, m3,` and `b` by minimizing the difference
# between its predicted prices and the actual prices in the training data.
# It essentially finds the line (or plane) that is closest to all the data points.
#
# ### Why Linear Regression for this case study?
# -   **Simplicity and Interpretability**: It's easy to understand how each feature influences the price.
#     If `m1` (for house size) is positive and large, it means larger houses significantly increase the price.
# -   **Good Baseline**: It often provides a strong baseline performance against which more complex models can be compared.
# -   **Efficiency**: It's computationally efficient, especially for datasets that exhibit a linear relationship.
#
# In summary, this case study will demonstrate how to build a basic yet effective house price prediction model
# using supervised learning and the Linear Regression algorithm, providing clear insights into its workings
# for both technical and non-technical audiences.

In [ ]:
# # Cell Number 2: Importing Essential Frameworks and Libraries
#
# This cell is crucial for setting up our environment. It brings in specialized tools
# (frameworks and libraries) that help us handle data, build our prediction model,
# and visualize our findings. Think of it as gathering all the right tools before
# starting a complex project.

# 1. Data Handling and Numerical Operations
# -----------------------------------------

# pandas: A powerful library for working with data tables (DataFrames).
# It's like a super-spreadsheet in Python, allowing us to easily load, clean, and manipulate our house data.
# Developers: Use for data ingestion, cleaning, and transformation.
# Testers: Understand that data will be processed through pandas for consistency.
# Solution Architects: Key for ETL (Extract, Transform, Load) processes in data pipelines.
# DevOps: Acknowledge its role in data preprocessing within ML workflows.
# Business Stakeholders: Essential for managing and understanding the raw data.
import pandas as pd

# numpy: The foundation for numerical computing in Python. It's great for performing
# mathematical operations on large arrays of numbers efficiently. Our house features and prices
# will often be stored and processed as numerical arrays.
# Developers: Core for mathematical operations and array handling.
# Testers: Results of calculations often rely on NumPy's precision.
# Solution Architects: Fundamental for any numerical heavy lifting.
# Business Stakeholders: Supports the underlying calculations that drive price predictions.
import numpy as np

# 2. Machine Learning Algorithms (Model Building)
# ------------------------------------------------

# scikit-learn (sklearn): This is the go-to library for traditional machine learning in Python.
# It provides ready-to-use algorithms, including Linear Regression, and tools for data splitting
# and model evaluation. It simplifies the process of building and testing our predictive model.
# Developers: Provides the Linear Regression algorithm and utility functions.
# Testers: Used to implement and test the model's accuracy.
# Solution Architects: Primary library for classical ML model deployment.
# Business Stakeholders: This is where our prediction model comes from.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# tensorflow: While we are using scikit-learn for Linear Regression in this case study,
# TensorFlow is an open-source library primarily used for deep learning and neural networks.
# It's like a heavy-duty tool for building very complex, advanced AI models.
# Although not strictly needed for basic Linear Regression, it's often imported for more
# sophisticated machine learning tasks that might follow. We include it here as a general ML framework.
# Developers: Crucial for advanced deep learning projects.
# Testers: Understand its potential for future, more complex models.
# Solution Architects: An option for scalable and complex AI systems.
# Business Stakeholders: Represents the cutting edge of AI development.
import tensorflow as tf

# 3. Data Visualization
# ---------------------

# matplotlib.pyplot: A comprehensive library for creating static, interactive, and animated
# visualizations in Python. We'll use it to plot graphs and charts to understand our data
# and visualize our model's performance. Seeing the data helps in understanding patterns.
# Developers: Used for plotting results and data distributions.
# Testers: Visually verify data patterns and model output.
# Solution Architects: Useful for integrating visual reporting.
# Business Stakeholders: Helps to clearly communicate data insights and model performance.
import matplotlib.pyplot as plt

# seaborn: Built on top of matplotlib, seaborn provides a high-level interface for drawing
# attractive and informative statistical graphics. It makes our visualizations look nicer
# and often requires less code for common statistical plots.
# Developers: Enhances data visualization capabilities.
# Testers: Improves the clarity of data analysis plots.
# Business Stakeholders: Makes complex data easier to grasp visually.
import seaborn as sns


# Confirmation Message
# --------------------
# This message confirms that all necessary tools have been successfully loaded
# and our environment is ready for the next steps in our house price prediction project.
print("All required data handling, machine learning, and visualization frameworks and libraries have been imported successfully!")

All required data handling, machine learning, and visualization frameworks and libraries have been imported successfully!

In [ ]:
# # Cell Number 3: Uploading the Dataset
#
# This step is crucial for bringing our raw data into the notebook environment.
# Think of it as bringing the blueprint of a house into our workshop before we start building.
# We need the data to train our house price prediction model.

# 1. Why are we doing this?
# --------------------------
# The machine learning model we are building needs data to learn from.
# This data contains examples of houses, their features (like size, number of bedrooms),
# and their actual selling prices. By uploading the dataset, we provide the 'experience'
# that our model will use to understand how house prices are determined.

# For Business Stakeholders:
# This is where the 'raw material' for our predictive insights comes from.
# Without this data, we cannot build a model to estimate house prices.

# For Layman:
# We're feeding the computer the facts it needs to learn about houses and their prices.
# It's like giving a student a textbook before an exam.

# For Technical Folks (Developers, Testers, Solution Architects, DevOps):
# We are ingesting the primary data source (e.g., CSV file) that will be used for
# training, validation, and testing of our Linear Regression model.
# This step ensures data availability within the Colab environment.

# 2. How are we doing this?
# --------------------------
# We will use a special function that creates an 'upload button'.
# When you click this button, you can select the dataset file (e.g., a CSV file)
# from your computer, and it will be loaded directly into this notebook.
# Once loaded, we'll confirm its successful upload and check its size.

# Import the files module from google.colab to enable file uploads.
# This module provides utilities specific to the Colab environment.
from google.colab import files

# Create a dictionary to hold the uploaded files.
# files.upload() will display a widget in the output cell, allowing the user to select files.
# Once a file is selected and uploaded, its content will be stored in this dictionary.
print("Please upload your dataset file now (e.g., a CSV file).")
uploaded = files.upload()

# Check if any file was uploaded.
if uploaded:
    # Assuming only one file is uploaded for this specific task.
    # Get the name of the first (and likely only) uploaded file.
    file_name = next(iter(uploaded))

    # Display a success message to the user.
    print(f"Dataset '{file_name}' has been uploaded successfully!")

    # Read the uploaded CSV file into a pandas DataFrame.
    # This converts the raw data into a structured table format that pandas can easily work with.
    # We use io.BytesIO because files.upload() returns file content as bytes.
    import io
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))

    # Display the number of rows (records) and columns (features) in the dataset.
    # This gives us an immediate understanding of the dataset's scale.
    print(f"Number of rows in the dataset: {df.shape[0]}")
    print(f"Number of columns in the dataset: {df.shape[1]}")

    # Display the first 5 rows of the DataFrame to get a quick preview of the data.
    # This helps in sanity-checking the data format and content.
    print("\nHere's a preview of your dataset:")
    display(df.head())
else:
    print("No file was uploaded. Please try again.")

Please upload your dataset file now (e.g., a CSV file).

Saving train.csv to train.csv
Dataset 'train.csv' has been uploaded successfully!
Number of rows in the dataset: 1460
Number of columns in the dataset: 81

Here's a preview of your dataset:

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
# # Cell Number 4: Next Steps in Building Our House Price Prediction Model
#
# Now that we've uploaded our dataset, it's time to start building our machine learning model.
# This cell will outline the typical stages a machine learning engineer follows to go from raw data
# to a functional predictive model, all explained in a way that everyone can understand.

# --- The Machine Learning Journey: Simple Steps ---

# Step 1: Data Understanding and Initial Cleaning (Coming Up Next)
# -----------------------------------------------------------------
# What is it?
# This involves taking a closer look at our uploaded data (the 'train.csv' file).
# We'll check for any missing information, incorrect entries, or data that might not be suitable
# for our model right away. We'll also identify the 'features' (inputs) and the 'target' (what we want to predict).

# For Business Stakeholders:
# We're making sure our foundational data is sound and ready for analysis.
# This ensures our predictions are based on reliable information.

# For Layman:
# We're just checking the ingredients before we start cooking to make sure everything is fresh and clean.
# We'll decide which parts of the house data are most important for predicting the price.

# For Technical Folks (Developers, Testers, Solution Architects, DevOps):
# This involves Exploratory Data Analysis (EDA), handling missing values (e.g., imputation, dropping rows/columns),
# outlier detection, and initial feature selection based on the problem statement.
# We will explicitly define our 'features' (X) and 'target' (y).


# Step 2: Data Preprocessing and Feature Selection (Focusing on Our 3 Features)
# -----------------------------------------------------------------------------
# What is it?
# This is where we prepare the data specifically for our Linear Regression model.
# We'll select the three key features we discussed earlier (e.g., house size, number of bedrooms, location score)
# from the 81 columns in our dataset. We'll also convert any text-based information into numbers if necessary,
# as machine learning models primarily work with numerical data.

# For Business Stakeholders:
# We are refining the data to highlight the most impactful factors for price prediction.
# This ensures our model focuses on the most relevant information.

# For Layman:
# We're picking out the most important characteristics of a house that really affect its price
# and making sure they are in a format the computer can understand.

# For Technical Folks:
# This involves selecting the chosen input features (e.g., 'GrLivArea', 'BedroomAbvGr', and a simplified 'OverallQual' or a numerical 'Neighborhood' encoding if applicable)
# and ensuring they are in a numerical format. This might include one-hot encoding for categorical variables if we choose to use them, or simply dropping non-numeric columns.


# Step 3: Splitting the Data (Training and Testing)
# --------------------------------------------------
# What is it?
# We divide our cleaned data into two main parts: a 'training set' and a 'testing set'.
# The training set is what our model will learn from, like a student studying for an exam.
# The testing set is used to evaluate how well our model performs on data it has never seen before, like the actual exam.

# For Business Stakeholders:
# This ensures we can objectively assess the model's accuracy and reliability on unseen data,
# preventing over-optimistic performance estimates.

# For Layman:
# We teach the model using one set of houses and then check its accuracy using a completely different set of houses.

# For Technical Folks:
# We will use `train_test_split` from `sklearn.model_selection` to split the dataset
# into `X_train`, `X_test`, `y_train`, and `y_test`. A common split is 70-80% for training and 20-30% for testing.


# Step 4: Training the Linear Regression Model
# -------------------------------------------
# What is it?
# This is where the machine learning magic happens! We feed our training data (features and actual prices)
# into the Linear Regression algorithm. The algorithm then "learns" the relationship between the features and prices,
# essentially drawing the 'best fit line' we discussed earlier.

# For Business Stakeholders:
# We are now building the core predictive engine that will estimate house prices.

# For Layman:
# The computer is now learning patterns from the houses we showed it, figuring out how different features
# influence the final price.

# For Technical Folks:
# We will instantiate `LinearRegression` from `sklearn.linear_model` and then call its `fit()` method
# using `X_train` and `y_train`.


# Step 5: Evaluating the Model's Performance
# ------------------------------------------
# What is it?
# After training, we need to see how good our model actually is. We'll use the 'testing set'
# (the data it hasn't seen before) to make predictions and then compare those predictions
# to the actual prices. We'll use metrics like 'Mean Squared Error' and 'R-squared'
# to quantify how accurate our model is.

# For Business Stakeholders:
# This step quantifies the reliability and accuracy of our house price predictions,
# helping us understand the model's business value.

# For Layman:
# We're checking how well the model performed on its 'exam' by comparing its guesses to the real answers.

# For Technical Folks:
# We will use the `predict()` method on `X_test` to get `y_pred`.
# Then, we'll calculate `mean_squared_error(y_test, y_pred)` and `r2_score(y_test, y_pred)`
# to assess the model's accuracy and explanatory power.


# Step 6: Making Predictions
# --------------------------
# What is it?
# Once our model is trained and evaluated, it's ready to make predictions on new, unseen house data.
# We can input the features of a brand new house and the model will provide an estimated price.

# For Business Stakeholders:
# This is the practical application of our model, providing actionable price estimates.

# For Layman:
# Now we can ask the computer to guess the price of any house, even one it's never seen before!

# For Technical Folks:
# We will use the trained model's `predict()` method with new input data (e.g., `model.predict([[new_size, new_bedrooms, new_location_score]])`).


# --- How to Increase Complexity (Future Steps) ---

# After completing these basic steps and understanding our simple model, we can explore ways to make it better:
# 1.  **More Features**: Incorporate more house characteristics (e.g., age of house, garage size, number of bathrooms).
# 2.  **Feature Engineering**: Create new, more insightful features from existing ones (e.g., total square footage = living area + basement area).
# 3.  **Advanced Algorithms**: Experiment with other machine learning algorithms like Random Forest, Gradient Boosting, or even Neural Networks (where TensorFlow comes in handy!).
# 4.  **Hyperparameter Tuning**: Optimize the settings of our chosen algorithm to get the best possible performance.
# 5.  **Cross-Validation**: Use more robust methods to evaluate the model's performance consistently across different data subsets.
# 6.  **Outlier Treatment**: More sophisticated methods to handle extreme values in the data.
# 7.  **Regularization**: Techniques to prevent the model from becoming too complex and overfitting the training data.

# For now, let's focus on building a solid foundation with our simple Linear Regression model.

In [ ]:
# # Cell Number 5: Step 1 - Data Understanding and Initial Cleaning
#
# This is our first practical step in preparing the data for our house price prediction model.
# Just like a chef checks their ingredients before cooking, we need to examine our data
# to ensure it's clean, complete, and in a format suitable for machine learning.

# 1. Why are we doing this step?
# ------------------------------
# Real-world data is rarely perfect. It often has missing values (empty spots),
# incorrect entries, or features that aren't immediately useful. If we feed 'dirty'
# data into our model, it will learn incorrectly and give us bad predictions.
# This step ensures our model learns from the best possible information.

# For Business Stakeholders:
# Cleaning the data ensures the integrity and reliability of our predictive model.
# It's about building a strong, trustworthy foundation for our price estimates.

# For Layman:
# We're tidying up the raw house information, like fixing typos or filling in blanks,
# so the computer can understand it perfectly and learn better.

# For Technical Folks (Developers, Testers, Solution Architects, DevOps):
# We perform preliminary Exploratory Data Analysis (EDA) to identify data quality issues.
# This includes checking data types, non-null counts, and distributions. Specifically,
# we will address missing values, which can severely impact model performance, and
# confirm our target variable (`SalePrice`).

# 2. Initial Data Inspection
# --------------------------
# Let's get a general overview of our data. This tells us about the data types
# in each column and how many non-missing values there are.
print("\n--- Initial Data Information ---")
df.info()

# 3. Handling Missing Values
# --------------------------
# Missing data is common. We need a strategy to deal with it. For simplicity,
# we'll use a straightforward approach for this basic model:
#   a. Remove columns that have too much missing information (e.g., more than 50% missing).
#      These columns might not provide enough useful data for our model.
#   b. For remaining numerical columns with some missing values, we'll fill them in
#      with the 'median' value of that column. The median is a good choice because
#      it's less affected by extreme values than the average.
#   c. For remaining categorical (text-based) columns with some missing values,
#      we'll fill them with the 'mode' (most frequent value) of that column.

print("\n--- Checking for Missing Values ---")
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values = missing_values[missing_values > 0]
print(missing_values)

# Identify columns to drop (e.g., > 50% missing)
# We dynamically calculate this, but common culprits are often 'Alley', 'PoolQC', 'Fence', 'MiscFeature'.
threshold = 0.5 * len(df) # Example: drop if more than 50% missing
columns_to_drop = missing_values[missing_values > threshold].index.tolist()

if columns_to_drop:
    print(f"\nDropping columns with more than 50% missing values: {', '.join(columns_to_drop)}")
    df = df.drop(columns=columns_to_drop)

# Re-check missing values after dropping columns
missing_values = df.isnull().sum()
missing_numerical = missing_values[df[missing_values.index].dtypes != 'object']
missing_categorical = missing_values[df[missing_values.index].dtypes == 'object']

# Impute numerical missing values with the median
for col in missing_numerical.index:
    if missing_numerical[col] > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        print(f"Imputed numerical column '{col}' with median value: {median_val}")

# Impute categorical missing values with the mode
for col in missing_categorical.index:
    if missing_categorical[col] > 0:
        mode_val = df[col].mode()[0]
        df[col].fillna(mode_val, inplace=True)
        print(f"Imputed categorical column '{col}' with mode value: {mode_val}")

# Confirm no more missing values
print("\n--- Missing Values After Cleaning ---")
print(df.isnull().sum().sum()) # Should be 0 if all handled

# 4. Identifying the Target Variable
# ----------------------------------
# Our goal is to predict 'SalePrice', so this will be our target variable (y).
# The remaining columns will be our features (X).
TARGET_VARIABLE = 'SalePrice'
if TARGET_VARIABLE in df.columns:
    print(f"\nTarget variable identified: '{TARGET_VARIABLE}'")
else:
    print(f"Error: Target variable '{TARGET_VARIABLE}' not found in the dataset.")

# 5. Final Confirmation
# ---------------------
# Displaying the final shape of the dataset after cleaning, and a preview.
print("\n--- Data Cleaning Complete! ---")
print(f"Cleaned dataset now has {df.shape[0]} rows and {df.shape[1]} columns.")
print("Here's a preview of the cleaned dataset:")
display(df.head())
print("Dataset has been successfully cleaned and is ready for feature selection!")

--- Initial Data Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

--- Checking for Missing Values ---
PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageQual        81
GarageFinish      81
GarageType        81
GarageYrBlt       81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtQual          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

Dropping columns with more than 50% missing values: PoolQC, MiscFeature, Alley, Fence, MasVnrType
Imputed numerical column 'LotFrontage' with median value: 69.0
Imputed numerical column 'MasVnrArea' with median value: 0.0
Imputed numerical column 'GarageYrBlt' with median value: 1980.0
Imputed categorical column 'BsmtQual' with mode value: TA
Imputed categorical column 'BsmtCond' with mode value: TA
Imputed categorical column 'BsmtExposure' with mode value: No
Imputed categorical column 'BsmtFinType1' with mode value: Unf
Imputed categorical column 'BsmtFinType2' with mode value: Unf
Imputed categorical column 'Electrical' with mode value: SBrkr
Imputed categorical column 'FireplaceQu' with mode value: Gd
Imputed categorical column 'GarageType' with mode value: Attchd
Imputed categorical column 'GarageFinish' with mode value: Unf
Imputed categorical column 'GarageQual' with mode value: TA
Imputed categorical column 'GarageCond' with mode value: TA

--- Missing Values After Cleaning ---
0

Target variable identified: 'SalePrice'

--- Data Cleaning Complete! ---
Cleaned dataset now has 1460 rows and 76 columns.
Here's a preview of the cleaned dataset:

/tmp/ipykernel_474/1755569656.py:70: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipykernel_474/1755569656.py:77: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

Dataset has been successfully cleaned and is ready for feature selection!

In [ ]:
#cell number 6#
# Step 2: Data Preprocessing and Feature Selection (Focusing on Our 3 Features)

## Cell Number 6: Step 2 - Data Preprocessing and Feature Selection

This is a critical stage where we distill our vast dataset down to the most relevant information for our model. We'll specifically focus on the three features we discussed initially to keep our model simple and understandable.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This step ensures our model focuses on the most impactful and easily understandable factors driving house prices. It's about translating complex raw data into clear, actionable inputs for our predictive system.

**For Layman:**
Imagine trying to describe a house. You wouldn't list every single nail and brick. You'd focus on the big things: how big it is, how nice it is, and if it has a garage. That's exactly what we're doing here – picking the key descriptors.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
Machine learning models perform best when fed with high-quality, relevant features. This step involves selecting a subset of the most predictive features from our cleaned dataset and transforming them into a format suitable for the `LinearRegression` algorithm. This reduces dimensionality, potentially improves model performance, and enhances interpretability.

### 2. Which features have we chosen and why?
-------------------------------------------
Based on general real estate knowledge and common practices in house price prediction, we've selected the following three features, which are strong indicators of a property's value:

1.  **`GrLivArea` (Above grade (ground) living area square feet):**
    *   **Reasoning:** This is often the single most important factor in determining house price. Larger living spaces generally command higher prices. It's a direct measure of the house's size.

2.  **`OverallQual` (Overall material and finish quality):**
    *   **Reasoning:** This feature captures the perceived quality of the house's materials and finishes (e.g., excellent, very good, average). A house with higher quality finishes and construction will naturally be more expensive. While it's an ordinal categorical variable (1-10), it's typically treated as numerical for linear models due to its ordered nature.

3.  **`GarageCars` (Size of garage in car capacity):**
    *   **Reasoning:** The presence and size of a garage are significant amenities that add considerable value to a home, especially in many markets. It's a clear indicator of additional functional space and utility.

These three features are numerical, directly available in our dataset, and intuitively strong predictors of `SalePrice`.

### 3. A brief note on Feature Engineering
---------------------------------------
**For Layman:**
Sometimes, to make our model even smarter, we might combine or transform existing features to create new, more informative ones. For example, we could combine 'total square footage' from 'basement' and 'above ground' areas.

**For Technical Folks:**
Feature engineering involves creating new features or modifying existing ones to improve model performance. While we are sticking to direct feature selection for this initial model, future iterations could involve creating interaction terms, polynomial features, or ratios from our raw data to capture more complex relationships. For this simple model, we will use the selected features as they are.

Now, let's select these features and separate our data into features (`X`) and the target variable (`y`).

In [ ]:
# Define the chosen features for our simple Linear Regression model.
# These are selected based on their intuitive impact on house prices and their numerical nature.
selected_features = ['GrLivArea', 'OverallQual', 'GarageCars']

# Define the target variable, which is what we want to predict.
TARGET_VARIABLE = 'SalePrice'

# Create the feature matrix (X) by selecting the chosen features from our cleaned DataFrame.
# .copy() is used to ensure we are working on a separate copy to avoid SettingWithCopyWarning later.
X = df[selected_features].copy()

# Create the target vector (y) containing the SalePrice.
y = df[TARGET_VARIABLE].copy()

# Display the first few rows of our feature matrix (X) to confirm the selection.
print("\n--- Selected Features (X) Preview ---")
display(X.head())

# Display the first few rows of our target variable (y) to confirm.
print("\n--- Target Variable (y) Preview ---")
display(y.head())

print(f"\nSuccessfully selected {len(selected_features)} features for our model.")
print("Data preprocessing and feature selection complete. Ready to split the data!")

--- Selected Features (X) Preview ---

   GrLivArea  OverallQual  GarageCars
0       1710            7           2
1       1262            6           2
2       1786            7           2
3       1717            7           3
4       2198            8           3

--- Target Variable (y) Preview ---

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

Successfully selected 3 features for our model.
Data preprocessing and feature selection complete. Ready to split the data!

## Cell Number 7: Step 3 - Splitting the Data (Training and Testing)

This is a critical step in building any robust machine learning model. Before we train our model, we need to divide our dataset into two distinct parts: a **training set** and a **testing set**. This ensures that we can objectively evaluate how well our model performs on data it has never seen before.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This step is about setting up a fair and unbiased evaluation for our model. By reserving a portion of data for testing, we can confidently assess how accurate our house price predictions will be in real-world scenarios, avoiding any 'cheating' by the model that has seen all the data during training.

**For Layman:**
Imagine a student studying for an exam. They use textbooks and practice problems to learn (training data). To truly know if they've learned, they take a completely new exam (testing data). We're doing the same for our model – letting it learn from some data and then testing its knowledge on unseen data.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
Splitting the data helps prevent **overfitting**. Overfitting occurs when a model learns the training data too well, including its noise and specific patterns, and consequently performs poorly on new, unseen data. By training on one subset and evaluating on another, we get a more realistic estimate of the model's generalization capability. The `train_test_split` function from `scikit-learn` is a standard practice for this.

### 2. How are we splitting the data?
------------------------------------
We will typically split the data with a common ratio, such as 70-80% for training and 20-30% for testing. For this case study, we'll use an **80/20 split**, meaning 80% of our data will be used to train the model and 20% will be held back to test its performance. We also use a `random_state` for reproducibility, ensuring that our split is the same every time we run the code.

Now, let's split our `X` (features) and `y` (target) into training and testing sets.

In [ ]:
# Import the train_test_split function from scikit-learn's model_selection module.
# This function is essential for dividing our dataset into training and testing subsets.
from sklearn.model_selection import train_test_split

# Split the features (X) and target (y) into training and testing sets.
# Parameters:
#   - test_size=0.2: This allocates 20% of the data to the testing set and 80% to the training set.
#   - random_state=42: This ensures reproducibility. If you run the code multiple times with the same random_state,
#     you will get the same split every time. This is crucial for consistent experimentation and debugging.
#   - X: Our feature matrix, containing 'GrLivArea', 'OverallQual', and 'GarageCars'.
#   - y: Our target vector, containing 'SalePrice'.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets to confirm the split.
# This helps verify that the data has been divided as expected.
print("--- Data Split Confirmation ---")
print(f"Shape of X_train (training features): {X_train.shape}")
print(f"Shape of X_test (testing features): {X_test.shape}")
print(f"Shape of y_train (training target): {y_train.shape}")
print(f"Shape of y_test (testing target): {y_test.shape}")

print("\nData successfully split into training and testing sets. Ready to train the model!")

--- Data Split Confirmation ---
Shape of X_train (training features): (1168, 3)
Shape of X_test (testing features): (292, 3)
Shape of y_train (training target): (1168,)
Shape of y_test (testing target): (292,)

Data successfully split into training and testing sets. Ready to train the model!

## Cell Number 8: Step 4 - Training the Linear Regression Model

This is the core of our machine learning process. After preparing and splitting our data, we now feed it to our chosen algorithm, Linear Regression, to learn the relationships between house features and their prices.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This is the stage where we create the actual prediction engine. By training the model, we enable it to generate house price estimates, which is the ultimate goal of our project. It transforms raw data into actionable business intelligence.

**For Layman:**
We're showing the computer all the houses in our `training set` (features and their actual prices) and telling it, "Figure out the rule! How does house size, quality, and garage size relate to the price?" The computer will then create a mathematical formula (our model) that captures this relationship.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
In this step, we instantiate the `LinearRegression` model from `scikit-learn` and use the `fit()` method to train it. The `fit()` method uses the `X_train` (training features) and `y_train` (training target prices) to learn the optimal coefficients (weights) and intercept for our linear equation. This process involves minimizing the sum of squared errors between the model's predictions and the actual `y_train` values.

### 2. How are we training the model?
------------------------------------
We will use `scikit-learn`'s `LinearRegression` object. First, we create an instance of the model. Then, we call its `fit()` method, passing in our training features (`X_train`) and our training target variable (`y_train`). This one line of code performs all the complex calculations needed to find the 'best fit line' for our data.

Let's train our Linear Regression model!

In [ ]:
# Import the LinearRegression model from scikit-learn's linear_model module.
# This is the algorithm we've chosen to predict house prices.
from sklearn.linear_model import LinearRegression

# Instantiate (create an instance of) the Linear Regression model.
# This initializes the model with default parameters.
model = LinearRegression()

# Train the model using our training data.
# The .fit() method takes the training features (X_train) and the training target (y_train).
# During this step, the model learns the relationship between the features and the target variable.
# It calculates the optimal coefficients for each feature and the intercept term.
print("--- Training the Linear Regression Model ---")
model.fit(X_train, y_train)

# After training, we can inspect the learned coefficients and the intercept.
# These values represent the 'rules' the model learned about how each feature influences price.
print("\nModel training complete!")
print(f"The model has learned {len(model.coef_)} coefficients for the features:")
for feature, coef in zip(X.columns, model.coef_):
    print(f"  - {feature}: {coef:.2f}")
print(f"  - Intercept (baseline price): {model.intercept_:.2f}")

print("\nLinear Regression model successfully trained. Ready for evaluation!")

--- Training the Linear Regression Model ---

Model training complete!
The model has learned 3 coefficients for the features:
  - GrLivArea: 47.23
  - OverallQual: 26772.49
  - GarageCars: 22239.46
  - Intercept (baseline price): -94208.72

Linear Regression model successfully trained. Ready for evaluation!

## Cell Number 9: Step 5 - Evaluating the Model's Performance

After training our model, it's crucial to understand how well it performs. This step assesses the quality of our predictions by comparing them against the actual values in our `testing set` – data the model has never seen before.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This step answers the fundamental question: "How good are our price predictions?" It quantifies the reliability and accuracy, helping to build confidence in the model's business value or identify areas for improvement.

**For Layman:**
We're checking the 'exam results' of our model. Did it learn well enough to guess the prices of new houses accurately? We're seeing if its predictions are close to the real prices.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
Model evaluation is critical to ensure generalization and avoid overfitting. We will use performance metrics on the `X_test` and `y_test` data. The primary metrics for regression tasks are:
*   **Mean Squared Error (MSE):** Measures the average squared difference between the estimated values and the actual value. It penalizes larger errors more severely.
*   **R-squared (R²):** Represents the proportion of the variance in the dependent variable that is predictable from the independent variables. A higher R² (closer to 1) indicates a better fit.

### 2. How are we evaluating the model?
------------------------------------
First, we'll ask our trained `model` to make predictions (`y_pred`) on the `X_test` features. Then, we'll use `scikit-learn`'s `mean_squared_error` and `r2_score` functions to compare these `y_pred` values against the actual `y_test` values.

Let's evaluate our model!

In [ ]:
# Make predictions on the test set.
# The model uses the relationships it learned during training to estimate prices for unseen houses.
print("--- Making Predictions on Test Data ---")
y_pred = model.predict(X_test)
print("Predictions generated successfully.")

# Import evaluation metrics from scikit-learn.
# These functions help us quantify the performance of our regression model.
from sklearn.metrics import mean_squared_error, r2_score

print("\n--- Evaluating Model Performance ---")

# Calculate Mean Squared Error (MSE).
# MSE is the average of the squared differences between the predicted and actual values.
# Lower MSE indicates better model performance.
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")

# Calculate Root Mean Squared Error (RMSE).
# RMSE is the square root of MSE and is often more interpretable as it's in the same units as the target variable.
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

# Calculate R-squared (R2) score.
# R2 represents the proportion of the variance in the dependent variable that is predictable from the independent variables.
# A value of 1.0 indicates a perfect fit, while 0.0 indicates that the model explains no variability.
r2 = r2_score(y_test, y_pred)
print(f"R-squared (R²): {r2:.2f}")

print("\nModel evaluation complete. Ready to make final predictions or explore further!")

--- Making Predictions on Test Data ---
Predictions generated successfully.

--- Evaluating Model Performance ---
Mean Squared Error (MSE): 1851765974.97
Root Mean Squared Error (RMSE): 43032.15
R-squared (R²): 0.76

Model evaluation complete. Ready to make final predictions or explore further!

## Cell Number 10: Step 6 - Making Predictions

This is the final, practical step where our trained and evaluated model gets to do what it was built for: predicting house prices! We can now input the characteristics of a hypothetical new house, and our model will estimate its `SalePrice`.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This is the ultimate deliverable of our project – a functional prediction tool. It allows for quick, data-driven estimations of property values, supporting decisions in real estate, investment, or lending.

**For Layman:**
After all that learning and testing, we can finally ask the computer: "Given a house with these features, what do you think its price will be?" It's the moment of truth where we get a practical answer.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
This step demonstrates the deployment readiness of the model for inference. We'll use the `predict()` method of our trained `LinearRegression` model. This process will take new input features (`X_new`) and output a predicted target value (`y_new_pred`). In a real-world scenario, this might be integrated into an API or an application.

### 2. How are we making predictions?
------------------------------------
We will create a new input for our model, which will be a set of values for our selected features: `GrLivArea`, `OverallQual`, and `GarageCars`. We'll then pass this input to our `model.predict()` method. Remember, the model expects these inputs in the same order and format it was trained on.

Let's make a prediction for a new house!

In [ ]:
# Define the features for a new, hypothetical house.
# The order of these values must match the order of features the model was trained on:
# ['GrLivArea', 'OverallQual', 'GarageCars']

# Example 1: A moderately sized, average quality house with a 2-car garage
# GrLivArea = 1500 sq ft, OverallQual = 6, GarageCars = 2
new_house_features_1 = pd.DataFrame([{
    'GrLivArea': 1500,
    'OverallQual': 6,
    'GarageCars': 2
}])

# Example 2: A larger, high-quality house with a 3-car garage
# GrLivArea = 2500 sq ft, OverallQual = 8, GarageCars = 3
new_house_features_2 = pd.DataFrame([{
    'GrLivArea': 2500,
    'OverallQual': 8,
    'GarageCars': 3
}])

# Example 3: A smaller, lower quality house with a 1-car garage
# GrLivArea = 1000 sq ft, OverallQual = 5, GarageCars = 1
new_house_features_3 = pd.DataFrame([{
    'GrLivArea': 1000,
    'OverallQual': 5,
    'GarageCars': 1
}])

print("--- Predicting Prices for New Houses ---")

# Make prediction for new_house_features_1
predicted_price_1 = model.predict(new_house_features_1)[0]
print(f"Predicted price for House 1 (GrLivArea=1500, OverallQual=6, GarageCars=2): ${predicted_price_1:,.2f}")

# Make prediction for new_house_features_2
predicted_price_2 = model.predict(new_house_features_2)[0]
print(f"Predicted price for House 2 (GrLivArea=2500, OverallQual=8, GarageCars=3): ${predicted_price_2:,.2f}")

# Make prediction for new_house_features_3
predicted_price_3 = model.predict(new_house_features_3)[0]
print(f"Predicted price for House 3 (GrLivArea=1000, OverallQual=5, GarageCars=1): ${predicted_price_3:,.2f}")

print("\nPredictions successfully made using the trained Linear Regression model!")

--- Predicting Prices for New Houses ---
Predicted price for House 1 (GrLivArea=1500, OverallQual=6, GarageCars=2): $181,747.90
Predicted price for House 2 (GrLivArea=2500, OverallQual=8, GarageCars=3): $304,760.84
Predicted price for House 3 (GrLivArea=1000, OverallQual=5, GarageCars=1): $109,121.69

Predictions successfully made using the trained Linear Regression model!

## Cell Number 11: Step 6 (Continued) - Interactive Prediction Interface

This section provides a simple, interactive way to utilize our trained Linear Regression model. You can plug in values for the three key features (`GrLivArea`, `OverallQual`, `GarageCars`) for any hypothetical house, and the model will provide an estimated `SalePrice`.

Crucially, we'll also give you context by finding houses in our *original dataset* that are most similar to your input and showing their actual sale prices. This helps you understand how your prediction aligns with historical data.

### 1. Why are we doing this step?
-------------------------------
**For Business Stakeholders:**
This is a hands-on tool that demonstrates the practical application of our model. It allows for quick, on-demand price estimates, which can be invaluable for initial assessments, valuation scenarios, or client discussions. Comparing it to existing sales provides a real-world sanity check.

**For Layman:**
This is where you get to play with the model! You can describe a house, and the computer will guess its price. We'll also show you what real houses that are like your described one actually sold for, so you can see if the guess is reasonable.

**For Technical Folks (Developers, Testers, Solution Architects, DevOps):**
This illustrates the model's inference capabilities and how it can be integrated into an interactive tool. The comparison with similar historical data serves as a practical form of model validation and interpretability, allowing users to understand the prediction in the context of known outcomes. The 'error ratio' in this context will represent how much our model's prediction deviates from the average sale price of truly similar historical properties.

### 2. How to use this interface?
------------------------------------
Below, you'll find a Python code cell. You can easily modify the values for `custom_gr_liv_area`, `custom_overall_qual`, and `custom_garage_cars` directly in the code. Once you run the cell, it will:

1.  **Predict the price** for your custom house.
2.  **Find the 5 most similar houses** in our original dataset based on your input features.
3.  **Display their actual `SalePrice`s**.
4.  **Calculate the average `SalePrice`** of these similar houses.
5.  **Calculate a 'Deviation Ratio'**: This shows how much our model's prediction differs (in percentage) from the average price of these similar historical houses. A small ratio means the prediction is close to what similar houses actually sold for.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances
import ipywidgets as widgets
from IPython.display import display

def predict_and_compare_house_price(
    gr_liv_area: int,
    overall_qual: int,
    garage_cars: int,
    model: LinearRegression,
    df_original: pd.DataFrame, # The original DataFrame (with SalePrice) to find similar houses
    features_for_model: list # List of features used by the model
):
    """
    Predicts house price for custom inputs and compares it to similar houses in the dataset.

    Args:
        gr_liv_area (int): Above grade (ground) living area in square feet.
        overall_qual (int): Overall material and finish quality (1-10).
        garage_cars (int): Size of garage in car capacity.
        model (LinearRegression): The trained Linear Regression model.
        df_original (pd.DataFrame): The original, cleaned DataFrame containing all features and SalePrice.
        features_for_model (list): A list of the feature names used by the model (e.g., ['GrLivArea', 'OverallQual', 'GarageCars']).

    Returns:
        None: Prints the prediction and comparison details.
    """

    # 1. Prepare the custom input for prediction
    custom_input = pd.DataFrame([{
        'GrLivArea': gr_liv_area,
        'OverallQual': overall_qual,
        'GarageCars': garage_cars
    }])

    # Ensure custom input columns match model's expected features order
    custom_input = custom_input[features_for_model]

    # 2. Get the predicted price
    predicted_price = model.predict(custom_input)[0]
    print(f"\n--- Custom House Prediction ---")
    print(f"Input Features: GrLivArea={gr_liv_area}, OverallQual={overall_qual}, GarageCars={garage_cars}")
    print(f"Predicted SalePrice: ${predicted_price:,.2f}")

    # 3. Find similar houses in the original dataset for context
    print("\n--- Finding Similar Houses in Historical Data ---")

    # Create a DataFrame from the original data with only the relevant features and SalePrice
    comparison_df = df_original[features_for_model + ['SalePrice']].copy()

    # Calculate Euclidean distance between the custom input and all houses in the comparison_df
    # We need to reshape the custom input to a 2D array for euclidean_distances
    distances = euclidean_distances(custom_input, comparison_df[features_for_model])

    # Add distances to the comparison_df and sort to find the closest matches
    comparison_df['distance'] = distances[0] # distances[0] because custom_input has only one row
    most_similar_houses = comparison_df.sort_values(by='distance').head(5)

    print("Top 5 Most Similar Houses (from original dataset) and their Actual Sale Prices:")
    for index, row in most_similar_houses.iterrows():
        print(f"  - GrLivArea={row['GrLivArea']:.0f}, OverallQual={row['OverallQual']:.0f}, GarageCars={row['GarageCars']:.0f} => Actual SalePrice: ${row['SalePrice']:,.2f}")

    # 4. Calculate average price of similar houses
    average_similar_price = most_similar_houses['SalePrice'].mean()
    print(f"\nAverage SalePrice of these 5 similar houses: ${average_similar_price:,.2f}")

    # 5. Calculate Deviation Ratio
    deviation = (predicted_price - average_similar_price) / average_similar_price * 100
    print(f"Model Prediction Deviation from Average of Similar Houses: {deviation:+.2f}%")

    if abs(deviation) < 5: # Arbitrary threshold for 'good' alignment
        print("This prediction aligns well with similar historical sales.")
    elif deviation > 0:
        print("The model predicts slightly higher than the average of similar historical sales.")
    else:
        print("The model predicts slightly lower than the average of similar historical sales.")

# --- Interactive Input Section ---
print("Please use the sliders/text box below to enter your custom house features:")

# Create widgets for interactive input
gr_liv_area_widget = widgets.IntText(
    value=1800,
    description='GrLivArea (sq ft):',
    min=300, max=5000, step=10,
    disabled=False
)

overall_qual_widget = widgets.IntSlider(
    value=7,
    description='OverallQual (1-10):',
    min=1, max=10, step=1,
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

garage_cars_widget = widgets.IntSlider(
    value=2,
    description='GarageCars (capacity):',
    min=0, max=4, step=1,
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

# Use interact to call the prediction function with the widget values
# We wrap the predict_and_compare_house_price function to pass fixed arguments (model, df, selected_features)
def interactive_prediction(gr_liv_area, overall_qual, garage_cars):
    predict_and_compare_house_price(
        gr_liv_area,
        overall_qual,
        garage_cars,
        model,
        df,
        selected_features
    )

# Display the interactive widgets
widgets.interact(interactive_prediction,
                 gr_liv_area=gr_liv_area_widget,
                 overall_qual=overall_qual_widget,
                 garage_cars=garage_cars_widget
                );

Please use the sliders/text box below to enter your custom house features:

interactive(children=(IntText(value=1800, description='GrLivArea (sq ft):', step=10), IntSlider(value=7, conti…

In [ ]:
#cell number 11#